# Generated by Django 4.1.4 on 2022-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakefeedback',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
