# Generated by Django 4.1.4 on 2022-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0003_alter_fakefeedback_options_alter_fakeusers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeusers',
            name='photo',
            field=models.ImageField(upload_to='fake_user_photo/'),
        ),
        migrations.AlterField(
            model_name='mainpicture',
            name='photo',
            field=models.ImageField(upload_to='media/main_picture/'),
        ),
    ]
