# Generated by Django 4.1.4 on 2022-12-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0005_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Заявки от клиентов'},
        ),
    ]
