# Generated by Django 4.1.4 on 2022-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0006_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_number',
            field=models.CharField(max_length=20),
        ),
    ]
