# Generated by Django 4.1.4 on 2022-12-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0007_alter_application_client_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakefeedback',
            name='mark',
        ),
        migrations.AddField(
            model_name='fakefeedback',
            name='title',
            field=models.CharField(default='default', help_text='Заголовок - будет выделен жирным шрифтом в отзывы', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fakefeedback',
            name='description',
            field=models.CharField(blank=True, help_text='Необязательное поле. Можешь делать себе какие-то пометки, либо можешь пустым', max_length=200),
        ),
        migrations.AlterField(
            model_name='fakefeedback',
            name='feedback_body',
            field=models.TextField(help_text='Тело отзыва - основная часть отзыва'),
        ),
        migrations.AlterField(
            model_name='fakeusers',
            name='description',
            field=models.CharField(blank=True, help_text='Необязательное поле. Можешь делать себе какие-то пометки, либо оставить пустым', max_length=200),
        ),
    ]
