# Generated by Django 4.1.4 on 2022-12-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0008_remove_fakefeedback_mark_fakefeedback_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakefeedback',
            name='description',
            field=models.CharField(blank=True, help_text='Необязательное поле. Можешь делать себе какие-то пометки, либо оставить пустым', max_length=200),
        ),
    ]
