# Generated by Django 4.1.4 on 2022-12-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0009_alter_fakefeedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpicture',
            name='photo',
            field=models.ImageField(upload_to='main_picture/'),
        ),
    ]
