# Generated by Django 4.1.4 on 2022-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0010_alter_mainpicture_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpicture',
            options={'verbose_name_plural': 'Слайды из карусели'},
        ),
        migrations.AlterField(
            model_name='fakefeedback',
            name='title',
            field=models.CharField(help_text='Заголовок - будет выделен жирным шрифтом в отзыве', max_length=50),
        ),
    ]
