# Generated by Django 4.1.4 on 2022-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukko_lake', '0013_alter_fakeusers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeusers',
            name='photo',
            field=models.URLField(help_text='Фото, чтобы адекватно отображаться в отзыве, должно быть размером 250x250. Сервис для изменения размеров фото: https://www.iloveimg.com/ru или любой подобный сервис. В идеале, чтобы начальный размер изображения был с соотношением стороон 1 к 1, к примеру, с таким размером: 950x950. В таком случае, при уменьшении размеров фото не нарушатся пропорции.'),
        ),
        migrations.AlterField(
            model_name='mainpicture',
            name='photo',
            field=models.URLField(),
        ),
    ]
